services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - photos_db:/app/database
    environment:
      - NODE_ENV=production
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    environment:
      - VUE_APP_BACKEND_URL=http://localhost:3000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  photos_db:
